config/routes.rb
Rails.application.routes.draw do
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  root 'posts#index'
  resources :tags

  resources :posts do
    resources :tagposts , controller: 'tagposts'
  end

  resources :users

  constraints subdomain: 'api' do
    namespace :api do
      resources :posts
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates_presence_of :title
    validates_presence_of :content
    has_many :tagPosts
    has_many :tags, through: :tagPosts
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user,except: [:show,:index]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(created_at: :desc)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @tags = @post.tags
    @availableTags = Tag.available(@post.id)
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "post-title-input"  %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "post-content-input" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<h1>Add Tag</h1>
<ul id="tagList">
    <% @tags.each do |tag| %>
        <li><%= tag.name %></li>
    <% end %>
</ul>
<form id="tagPostForm" action="/posts/<%= @post.id %>/tagposts" method="post">
  <select id="tag_id" name="tag_id">
    <% @availableTags.each do |tag| %>
      <option value="<%= tag.id %>"><%= tag.name %></option>
    <% end %>
  </select>
  <input  type="hidden" id="post_id"  name="post_id" value="<%= @post.id %>" />
  <button id="add-tag">Add</button>
</form>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="blog-list-page">
  <% @posts.each do |post| %>
  <div class="post-summarize">
    <div class="post-date">
        <%= post.created_at.strftime("%A, %B %d, %Y") %>
    </div>
    <div class="post-title">
      <%= link_to post.title, post %>
    </div>
    <ul class="tags">
      <% post.tags.each do |tag| %>
        <li class="tag <%= tag.color %>"><%= tag.name %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% content_for :meta do %>
 <meta property="og:site_name" content="Cao Tan Thanh's Blog"/>
 <meta property="og:url" content="<%= post_url(@post.id) %>"/>
 <meta property="og:title" content="<%= @post.title.gsub(/"/, '') %>"/>
 <meta property="og:type" content="cttblog:post"/>
 <meta property="og:description" content='<%= @post.content.truncate(200).gsub(/"/, '').squish %>' />
<% end %>
<p id="notice"><%= notice %></p>
<div class="blog-list-page">
  <div class="post-item">
    <div class="post-date centerize">
        <%= @post.created_at.strftime("%B %d, %Y") %>
    </div>
    <div class="post-title">
      <%= link_to @post.title, @post,:class => "slabText" %>
    </div>
    <div class="post-content">
      <%=raw @post.content.gsub(/\n/, '<br/>') %>
    </div>
    <ul class="tags">
      <% @post.tags.each do |tag| %>
        <li class="tag <%= tag.color %>"><%= tag.name %></li>
      <% end %>
    </ul>
  </div>
</div>